#!/usr/bin/env bash
# This will read an S3 file to stdout.
#
# Example:
# ./read jex-env-files foo.env

EXAMPLE="| ./read BUCKET FILE"
BUCKET=${1:?"BUCKET not specified. ${EXAMPLE}"}
FILE=${2:?"FILE not specified. ${EXAMPLE}"}

aws s3 cp s3://$BUCKET/$FILE -
