#!/usr/bin/env bash
# This will update something in a file in S3.
#
# Example:
# ./update jex-env-files foo.env VERSION 9.9

EXAMPLE=" | ./update BUCKET FILE PATTERN REPLACEMENT"
BUCKET=${1:?"BUCKET not specified. ${EXAMPLE}"}
FILE=${2:?"FILE not specified. ${EXAMPLE}"}
PATTERN=${3:?"PATTERN not specified. ${EXAMPLE}"}
REPLACEMENT=${4:?"REPLACEMENT not specified. ${EXAMPLE}"}

./read $BUCKET $FILE | \
  sed "s/$PATTERN/$REPLACEMENT/g" | \
  ./write $BUCKET $FILE
