#!/usr/bin/env bash
# This will write an S3 file from stdin.
#
# Example:
# echo "hello" | ./write jex-env-files greetings

EXAMPLE="| echo \"hello\" | ./write BUCKET FILE"
BUCKET=${1:?"BUCKET not specified. ${EXAMPLE}"}
FILE=${2:?"FILE not specified. ${EXAMPLE}"}

aws s3 cp - s3://$BUCKET/$FILE
